In [7]:
import duckdb
conn = duckdb.connect('../../local.duckdb')

In [9]:
conn.sql("summarize stg_providers").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,practitioner_id,VARCHAR,1003002809,1992999122,50741,None,<NA>,None,None,None,44332,0.0
1,npi,VARCHAR,1003002809,1992999122,50741,None,<NA>,None,None,None,44332,0.0
2,provider_first_name,VARCHAR,A,Zvi,8686,None,<NA>,None,None,None,44332,0.0
3,provider_last_name,VARCHAR,Aaboe,Zyniewicz,24192,None,<NA>,None,None,None,44332,0.0
4,practice_affiliation,VARCHAR,None,None,0,None,<NA>,None,None,None,44332,100.0
5,specialty,VARCHAR,Acupuncturist,Wound Care,109,None,<NA>,None,None,None,44332,0.0
6,sub_specialty,VARCHAR,None,None,0,None,<NA>,None,None,None,44332,100.0
7,data_source,VARCHAR,None,None,0,None,<NA>,None,None,None,44332,100.0
8,tuva_last_run,TIMESTAMP,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,1,2025-12-28 18:29:03.120763,<NA>,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,44332,0.0

In [10]:
conn.sql("summarize stg_immunizations").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,immunization_id,VARCHAR,10011-2fc4c21a-8e7c-14ce-86cd-05f3e968f9a7-140,13360-4d70f4cd-d80b-fe9c-4c18-0820f3031593-140,328,None,<NA>,None,None,None,355,0.0
1,person_id,VARCHAR,10011,13360,86,None,<NA>,None,None,None,355,0.0
2,patient_id,VARCHAR,10011,13360,86,None,<NA>,None,None,None,355,0.0
3,encounter_id,VARCHAR,10011-2fc4c21a-8e7c-14ce-86cd-05f3e968f9a7,13360-4d70f4cd-d80b-fe9c-4c18-0820f3031593,269,None,<NA>,None,None,None,355,0.0
4,source_code_type,VARCHAR,cvx,cvx,1,None,<NA>,None,None,None,355,0.0
5,source_code,VARCHAR,03,83,18,None,<NA>,None,None,None,355,0.0
6,source_description,VARCHAR,DTaP,zoster vaccine live,17,None,<NA>,None,None,None,355,0.0
7,normalized_code_type,VARCHAR,cvx,cvx,1,None,<NA>,None,None,None,355,0.0
8,normalized_code,VARCHAR,03,83,18,None,<NA>,None,None,None,355,0.0
9,normalized_description,VARCHAR,DTaP,zoster vaccine live,17,None,<NA>,None,None,None,355,0.0
10,mapping_method,VARCHAR,manual,manual,1,None,<NA>,None,None,None,355,0.0
11,status,VARCHAR,Completed,Completed,1,None,<NA>,None,None,None,355,0.0
12,status_reason,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
13,occurrence_date,DATE,2014-11-29,2018-12-23,98,2017-03-14 10:49:00.84507,<NA>,2016-02-27,2017-02-26,2018-03-01,355,0.0
14,source_dose,VARCHAR,1,1,1,None,<NA>,None,None,None,355,0.0
15,normalized_dose,VARCHAR,1,1,1,None,<NA>,None,None,None,355,0.0
16,lot_number,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
17,body_site,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
18,route,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
19,location_id,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
20,practitioner_id,VARCHAR,None,None,0,None,<NA>,None,None,None,355,100.0
21,data_source,VARCHAR,emr,emr,1,None,<NA>,None,None,None,355,0.0
22,tuva_last_run,TIMESTAMP,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,1,2025-12-28 18:29:03.120763,<NA>,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,2025-12-28 18:29:03.120763,355,0.0