In [1]:
import duckdb

con = duckdb.connect('../local.duckdb', read_only=True)

con.sql("""
    SELECT name 
    FROM sqlite_master 
    WHERE type='table' 
    AND (name LIKE 'dim_%' OR name LIKE 'fact_immunizations%')
    ORDER BY name
""").show()

┌────────────────────┐
│        name        │
│      varchar       │
├────────────────────┤
│ dim_cancer_type    │
│ dim_care_setting   │
│ dim_date           │
│ dim_imm_patient    │
│ dim_patient        │
│ dim_provider       │
│ dim_spend_bucket   │
│ dim_vaccine        │
│ fact_immunizations │
└────────────────────┘

In [2]:
con.sql("""
        SELECT *
        FROM fact_immunizations
        """).df()

,immunization_sk,patient_sk,provider_sk,vaccine_sk,date_sk,immunization_id,encounter_id,person_id,patient_id,immunization_status,dose_number,occurrence_date,data_source,paid_amount,allowed_amount,total_cost_amount,claim_count,immunization_count
0,1ebe0421b9700b94a740911ae57ec9a8,70431e77d378d760c3c5456519f06efe,f14cc5cdce0420f4a5a6b6d9d7b85f39,44f683a84163b3523afe57c2e008bc8c,d9e5bf7658f913a2a6d38ea3c8b58183,11059-5d83970a-71a8-dcf3-4cb5-3363a0a245c6-62,11059-5d83970a-71a8-dcf3-4cb5-3363a0a245c6,11059,11059,Completed,1,2017-02-23,emr,100.14,8.39,0.0,2,1
1,810e90b121ce3f5436f19be285d9ea42,70431e77d378d760c3c5456519f06efe,f14cc5cdce0420f4a5a6b6d9d7b85f39,1385974ed5904a438616ff7bdb3f7439,d9e5bf7658f913a2a6d38ea3c8b58183,11059-5d83970a-71a8-dcf3-4cb5-3363a0a245c6-140,11059-5d83970a-71a8-dcf3-4cb5-3363a0a245c6,11059,11059,Completed,1,2017-02-23,emr,100.14,8.39,0.0,2,1
2,154cee8f954816ee7486a57a2b9974f0,f376b8ae6217d18ca5ebcc8b402b63a1,f14cc5cdce0420f4a5a6b6d9d7b85f39,1385974ed5904a438616ff7bdb3f7439,f075a4508c80da1eee0bebf4d85433ee,10156-8ead24d4-5955-424b-a2d9-fafcc55bae09-140,10156-8ead24d4-5955-424b-a2d9-fafcc55bae09,10156,10156,Completed,1,2017-12-03,emr,59.90,75.71,0.0,1,1
3,c914aad4b273aa7056aba3c6ae19d9ab,08058bf500242562c0d031ff830ad094,f14cc5cdce0420f4a5a6b6d9d7b85f39,1385974ed5904a438616ff7bdb3f7439,1cacb4a1a1bc93062bce9cf6d5f89110,11923-ef0fde3e-e018-3aa5-eefd-2052a11198a9-140,11923-ef0fde3e-e018-3aa5-eefd-2052a11198a9,11923,11923,Completed,1,2017-01-22,emr,171.39,228.79,0.0,2,1
4,b65789c152a42d57f55c0274d1839982,aa68c75c4a77c87f97fb686b2f068676,f14cc5cdce0420f4a5a6b6d9d7b85f39,73278a4a86960eeb576a8fd4c9ec6997,84b46daf1c71da009e71ff24668b7582,1003-366c32f6-6d5f-2ed9-495f-3687fe5160fb-113,1003-366c32f6-6d5f-2ed9-495f-3687fe5160fb,1003,1003,Completed,1,2018-05-01,emr,52.52,10.66,0.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,6d4d55b48e5f98ff7754198c3ee59d24,547e254ad67a3f2b4cd98de28e663293,f14cc5cdce0420f4a5a6b6d9d7b85f39,17e62166fc8586dfa4d1bc0e1742c08b,6cf939962176b8f9d42b1046dad65ea9,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d-43,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d,10630,10630,Completed,1,2018-05-10,emr,0.00,0.00,0.0,0,1
351,38ce057dbfad9815153fb70e576bc1e3,70431e77d378d760c3c5456519f06efe,f14cc5cdce0420f4a5a6b6d9d7b85f39,44f683a84163b3523afe57c2e008bc8c,02059d607bef2a7b1ab830b5f2897085,11059-efb685ba-a1ac-8de9-da6b-02c8d168fec7-62,11059-efb685ba-a1ac-8de9-da6b-02c8d168fec7,11059,11059,Completed,1,2018-03-01,emr,0.00,0.00,0.0,0,1
352,625e87b69f912fb1244d4f3b454e9d6e,547e254ad67a3f2b4cd98de28e663293,f14cc5cdce0420f4a5a6b6d9d7b85f39,5fd0b37cd7dbbb00f97ba6ce92bf5add,6cf939962176b8f9d42b1046dad65ea9,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d-114,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d,10630,10630,Completed,1,2018-05-10,emr,0.00,0.00,0.0,0,1
353,ca5ef93187199d7efce297b1df6ed0ae,3eb46aa5d93b7a5939616af91addfa88,f14cc5cdce0420f4a5a6b6d9d7b85f39,73278a4a86960eeb576a8fd4c9ec6997,84b46daf1c71da009e71ff24668b7582,10936-366c32f6-6d5f-2ed9-495f-3687fe5160fb-113,10936-366c32f6-6d5f-2ed9-495f-3687fe5160fb,10936,10936,Completed,1,2018-05-01,emr,0.00,0.00,0.0,0,1
354,a5571fd872a3a49a18bd46e598f3e00c,547e254ad67a3f2b4cd98de28e663293,f14cc5cdce0420f4a5a6b6d9d7b85f39,73278a4a86960eeb576a8fd4c9ec6997,6cf939962176b8f9d42b1046dad65ea9,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d-113,10630-122d5886-d4a6-2648-b9b2-8c87a7497b2d,10630,10630,Completed,1,2018-05-10,emr,0.00,0.00,0.0,0,1

In [3]:
con.sql("""
        SELECT *
        FROM dim_imm_patient
        """).df()

,patient_sk,person_id,patient_id,total_immunizations,distinct_vaccines,first_immunization_date,last_immunization_date
0,61cb6463141119abd41762825ad4f9cd,12955,12955,5,2,2015-09-20,2018-10-07
1,74105d373a71b517ed650caabb9c2cb8,10106,10106,8,4,2016-02-18,2018-03-01
2,840aae12cd1e21200e2b729b1e151323,11612,11612,2,1,2015-11-14,2017-06-24
3,47af10edfc4c96329531345635a4baa9,12601,12601,6,3,2016-09-03,2018-09-15
4,c0e2bf725db7e7a854b8c181154d8059,13113,13113,6,3,2016-04-26,2018-09-11
...,...,...,...,...,...,...,...
69,153e7487e891837a34233c390e64c710,11802,11802,2,1,2015-11-14,2017-06-24
70,ea2d131c2a2c1b6b2956919af13a76c5,13231,13231,4,2,2016-03-29,2018-04-10
71,9352d6848d5f8868810d431499d34639,12403,12403,5,2,2015-10-02,2018-10-19
72,ab9a3f4c92c0f50204a1fe6dbf2e1d0a,12380,12380,5,2,2015-09-23,2018-10-10
73,b83b4b4fb7dee46fd2e688f76e3f3928,12710,12710,8,4,2016-02-18,2018-03-01